### ISSUE TITLE
[FEAT] API Endpoint For Organisation Creation by users

### ISSUE THREAD

**Issue by Cyberguru1** [hngprojects/hng_boilerplate_golang_web#16]
## Description

Develop a backend API for creating organisations, including authentication and authorization checks, input validation, and error handling.

## Acceptance Criteria

1. **Authentication Middleware**

   - Implement middleware to ensure the user is authenticated using JWT.
   - If authentication fails, return a `401 Unauthorized` status code.
   - If authenticated, proceed with the request.
2. **Create Organisation Endpoint**

   - Before creating an organisation you need an access token
     - create a user with a post request to this endpoint `HTTP POST` `/api/v1/auth/users/signup`
     - **Request Body** :
       ```json
       {
           "email": "testuser@gmail.com",
           "first_name": "test",
           "last_name": "user",
           "password": "strongUserP@ssw0rd",
           "username": "testuser"
       }
       ```
     - **Response Body**:
        ```json
        {
            "status": "success",
            "code": 201,
            "message": "user created successfully",
            "data": {
                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3Jpc2VkIjp0cnVlLCJleHAiOjE3MjIxNjM4NDQsInVzZXJfaWQiOiIwMTkwZDRlYS01MGE3LTcyMTctYTZhOS03YjgyZTljODViNWYifQ.Zl99Quxrrpu8UdAFYp-4CjI7gR70gb5m6q-3yfOn0mw",
                "email": "testuser@gmail.com",
                "expires_in": "2024-07-28T05:50:44.266839645-05:00",
                "first_name": "Test",
                "last_name": "User",
                "phone": "",
                "username": "testuser"
            }
        }
        ```
     - Use the return `access_token` in the Authorization header
       ```text
       Authorization:  Bearer {access_token}
       ```
 
   - Make a `HTTP POST` to `/api/v1/organisations`.
    - Creates a new organisation with a `201 Created` status code if the user request is valid.
    - **Request Body**:

        ```json
        {
            "email": "testuser@gmail.com",
            "name": "test Org",
            "description": "Some random description about vibranium",
            "state":       "test",
            "industry":    "user",
            "type":        "type1",
            "address":     "wakanda land",
            "country":     "wakanda"
        }
        ```
        
    - **Successful Response**:
        
        ```json
        {
            "status": "success",
            "code": 201,
            "message": "organisation created successfully",
            "data": {
                "id": "0190d4fd-0647-7218-8505-98f64f619956",
                "name": "test org",
                "description": "some random description about vibranium",
                "email": "testuser@gmail.com",
                "state": "test",
                "industry": "user",
                "type": "type1",
                "address": "wakanda land",
                "country": "wakanda",
                "owner_id": "0190d4ea-50a7-7217-a6a9-7b82e9c85b5f",
                "Users": null,
                "created_at": "2024-07-21T06:11:10.40741298-05:00",
                "updated_at": "2024-07-21T06:11:10.40741298-05:00"
            }
        }
        ```
        
    - **Unsuccessful Response**:
        
        ```json
        {
            "status": "error",
            "code": 400,
            "message": "error message",
            "error": {}
        }
        ```
        
    - **Validation Error Response**:
        
        ```json
        {
            "status": "error",
            "code": 422,
            "message": "Validation failed",
            "error": {
                "feild": "message"
            }
        }
        ```
        
    - **Unauthenticated Error Response**:
        
        ```json
        {
            "status": "error",
            "code": 401,
            "message": "Token could not be found!",
            "error": "Unauthorized"
        }
        ```

### Database Design

```plaintext
Table organisations {
  id uuid [primary key]
  owner_id uuid [foreign key to users(id)]
  name varchar(255)
  email varchar(255) [unique]
  industry varchar(255)
  type varchar(255)
  country varchar(255)
  address varchar(255)
  state varchar(255)
  description text
  created_at timestamp
  updated_at timestamp
}

Table organisations_user {
  user_id uuid [foreign key to users(id)]
  organisation_id uuid [foreign key to organisations(id)]
  created_at timestamp
  updated_at timestamp
}

Ref: users.id < organisations_user.user_id
Ref: organisations.id < organisations_user.organisation_id
```

## Purpose

Provide a backend service that allows admins to create new organisations, ensuring proper authentication, authorization, and validation.

## Requirements

- [X] Implement middleware for  JWT authentication.
- [X] Develop server-side logic to create a new organisation.
- [X] Develop server-side logic to bind user to the created organisation.
- [X] Validate each field in the request json

## Expected Outcome

The API endpoint allows users to create new organisations with appropriate validation and authentication

## Task

- [X] Create the endpoint `HTTP POST /api/v1/organisations` to create new organisations.
- [X] Implement authentication middleware to validate JWT tokens.
- [X] Validate all fields in the request body.
- [X] Write unit tests for all scenarios, including successful creation, validation errors, and authentication/authorization checks.
- [X] Perform security testing to ensure data protection and compliance.

## Testing

- Write unit tests for successful organisation creation.
- Write unit tests for fields validation.
- Write unit tests for bad client requests.
- Write unit tests for authentication checks.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios for creating organisations, including edge cases and error handling.

**Comment by Cyberguru1** [comment]
double approved issue from [issue #102](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/102)
