### ISSUE TITLE
FEAT: Get users waitlist 

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#201]
# API Endpoint: Get Waitlist

## Description
Develop an API endpoint to retrieve the waitlist with proper authentication and validation.

## Acceptance Criteria
* The endpoint should be accessible at `api/v1/waitlist`.
* The endpoint should accept HTTP GET requests.
* The endpoint should support pagination with `page` and `limit` query parameters.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer <token>**

### Request
* Query parameters for pagination: `api/v1/waitlist?page=1&limit=10`.
* No request body is required.

### Response

**On successful retrieval:**
```json
{
  "status": "success",
  "status_code": 200,
  "message": "Waitlist retrieved successfully",
  "data": [
    {
      "id": "0190ff9e-568c-7faa-ac3a-fbf56ee85d56",
      "name": "ajinx1006",
      "email": "iamcybertest+6@gmail.com",
      "created_at": "2024-07-29T18:51:25.335318+01:00",
      "updated_at": "2024-07-29T18:51:25.335318+01:00"
    },
  ],
  "pagination": {
    "current_page": 1,
    "page_count": 1,
    "total_pages_count": 1
  }
}
```

_Unsuccessful Response:_
 ```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

 _Authorisation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

 ## Purpose
Provides a backend service that allows authorized users to retrieve the waitlist with pagination support.

## Requirements
* Develop server-side logic to retrieve the waitlist.
* Ensure only users with appropriate permissions can access the data.
* Implement proper error handling and status code responses.

## Expected Outcome
* API endpoint allows retrieval of the waitlist with appropriate authentication and error handling.

## Tasks
* [ ] Create an endpoint GET `api/v1/waitlist` to retrieve the waitlist.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the data.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for retrieving the waitlist.
* [ ] Perform security testing to ensure only authorized users can access the data.

## Testing
* Write integration tests for the end-to-end get waitlist flow.
* Test various scenarios:
  * Retrieving waitlist items.
  * Attempting to retrieve waitlist items without authentication.
