### ISSUE TITLE
FEAT: Get all users 

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#202]
## Description
Develop an API endpoint to retrieve all users with proper authentication, validation, and pagination support.

### Acceptance Criteria
* The endpoint should be accessible at `GET api/v1/users`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The endpoint should support pagination.

Authorization: Bearer <token>

#### Request
* No request body is required.
* Pagination parameters should be included in the query string, e.g., `api/v1/users?page=1&limit=10`.

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of users.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Users retrieved successfully",
    "data": [
        {
            "id": "0190e179-2c85-7c6c-8f9c-503ed1803691",
            "name": "hm1",
            "email": "hmadmin@example.com",
            "profile": {
                "profile_id": "",
                "first_name": "",
                "last_name": "",
                "phone": "",
                "avatar_url": "",
                "user_id": "",
                "created_at": "0001-01-01T00:00:00Z",
                "updated_at": "0001-01-01T00:00:00Z"
            },
            "organisations": null,
            "products": null,
            "created_at": "2024-07-23T22:22:13.255539+01:00",
            "updated_at": "2024-07-24T18:50:14.747494+01:00",
            "role": 2
        },
        ...
    ],
    "pagination": [
        {
            "current_page": 1,
            "page_count": 1,
            "total_pages_count": 1
        }
    ]
}
```

_Unsuccessful Response:_
 ```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

 _Authorisation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

### Purpose
Provides a backend service that allows authorized users to retrieve all users with pagination support.

### Requirements
* Develop server-side logic to retrieve the users.
* Ensure only users with appropriate permissions can access the data.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of all users with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET api/v1/users` to retrieve the users.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the data.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for retrieving the users.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end get users flow.
* Test various scenarios:
  * Retrieving users.
  * Attempting to retrieve users without authentication.
