### ISSUE TITLE
FEAT: Get all emails for newsletter

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#203]
## Description
Develop an API endpoint to retrieve all newsletters with proper authentication, validation, and pagination support.

### Acceptance Criteria
* The endpoint should be accessible at `GET api/v1/newsletter`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The endpoint should support pagination.

Authorization: Bearer <token>

#### Request
* No request body is required.
* Pagination parameters should be included in the query string, e.g., `api/v1/newsletter?page=1&limit=10`.

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of newsletters.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Newsletters email retrieved successfully",
    "data": [
        {
            "id": "0190ff8c-96d7-79e7-a13d-154449084572",
            "email": "iamcybertest+4@gmail.com",
            "created_at": "2024-07-29T18:32:02.135934+01:00",
            "updated_at": "2024-07-29T18:32:02.135934+01:00"
        },
        ...
    ],
    "pagination": [
        {
            "current_page": 1,
            "page_count": 1,
            "total_pages_count": 1
        }
    ]
}
```

_Unsuccessful Response:_
 ```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

 _Authorisation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```
 
### Purpose
Provides a backend service that allows authorized users to retrieve all newsletters with pagination support.

### Requirements
* Develop server-side logic to retrieve the newsletters.
* Ensure only users with appropriate permissions can access the data.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of all newsletters with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET api/v1/newsletter` to retrieve the newsletters.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the data.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for retrieving the newsletters.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end get newsletters flow.
* Test various scenarios:
  * Retrieving newsletters.
  * Attempting to retrieve newsletters without authentication.
