### ISSUE TITLE
FEAT: Delete email from getting newsletter

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#204]
## Description
Develop an API endpoint to delete a specific newsletter by its ID with proper authentication and validation.

### Acceptance Criteria
* The endpoint should be accessible at `DELETE api/v1/newsletter/{id}`.
* The endpoint should accept HTTP DELETE requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer <token>

#### Request
* The newsletter ID should be included in the URL path.
* No request body is required.

#### Response
* On successful deletion, the API should return a 200 OK status code with a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Newsletter email deleted successfully"
}

```

_Unsuccessful Response:_
 ```json
{
    "status": "error",
    "status_code": 400,
    "message": "record not found"
}
 ```

 _Authorisation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

### Purpose
Provides a backend service that allows authorized users to delete a specific newsletter by its ID.

### Requirements
* Develop server-side logic to delete the newsletter by its ID.
* Ensure only users with appropriate permissions can access the data.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows deletion of a specific newsletter with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `DELETE api/v1/newsletter/{id}` to delete the newsletter.
* [ ] Implement server-side logic to handle successful and failed deletion requests.
* [ ] Ensure the user has the proper permissions to delete the newsletter.
* [ ] Implement proper error handling for various scenarios (record not found, unauthorized access, etc.).
* [ ] Write integration tests for deleting the newsletter.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end delete newsletter flow.
* Test various scenarios:
  * Deleting an existing newsletter.
  * Attempting to delete a newsletter that does not exist.
  * Attempting to delete a newsletter without authentication.
