### ISSUE TITLE
FEAT: Super admin create FAQ

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#206]
## Description
Develop an API endpoint to create a new FAQ entry with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `POST api/v1/faq`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to create a new FAQ.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
      "question": "who killed david jane3",
      "answer": "ajinx007"
  }
```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "FAQ added successfully"
}
```

_Unsuccessful Response:_
* If the question already exists:
 ```json
{
    "status": "error",
    "status_code": 400,
    "message": "question exists"
}
 ```
 * If there is any other error or invalid input:
  ```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

 _Authorisation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

 _Validation Error Response::_
 
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed"
}
 ```

### Purpose
Provides a backend service that allows authorized users to create a new FAQ entry.

### Requirements
* Develop server-side logic to handle the creation of a new FAQ.
* Ensure only users with appropriate permissions can create a new FAQ.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows creation of a new FAQ with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST api/v1/faq` to create a new FAQ.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Ensure the user has the proper permissions to create the FAQ.
* [ ] Implement proper error handling for various scenarios (question exists, unauthorized access, etc.).
* [ ] Write integration tests for creating the FAQ.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end create FAQ flow.
* Test various scenarios:
  * Creating a new FAQ with valid data.
  * Attempting to create an FAQ with a duplicate question.
  * Attempting to create an FAQ without authentication.
