### ISSUE TITLE
FEAT: Get all faqs

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#207]
## Description
Develop an API endpoint to retrieve all FAQs with pagination support. No authorization is required to access this endpoint.

### Acceptance Criteria
* The endpoint should be accessible at `GET api/v1/faq`.
* The endpoint should accept HTTP GET requests.
* No authentication is required to access the endpoint.
* The endpoint should support pagination.

#### Request
* No request body is required.
* Pagination parameters should be included in the query string, e.g., `api/v1/faq?page=1&limit=10`.

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of FAQs.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "FAQ retrieved successfully",
    "data": [
        {
            "id": "019102fa-5866-7cfe-9cb6-32c70eb35de9",
            "question": "who killed david jane37",
            "answer": "ajinx007",
            "created_at": "2024-07-30T10:30:46.758745+01:00",
            "updated_at": "2024-07-30T10:30:46.758745+01:00"
        },
        ...
    ],
    "pagination": [
        {
            "current_page": 1,
            "page_count": 1,
            "total_pages_count": 1
        }
    ]
}
```

_Unsuccessful Response:_
  ```json
{
    "status": "error",
    "status_code": 400,
    "message": "error"
}
 ```

### Purpose
Provides a backend service that allows retrieval of all FAQs with pagination support without requiring authorization.

### Requirements
* Develop server-side logic to retrieve all FAQs.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of all FAQs with pagination and proper error handling.

### Tasks
* [ ] Create an endpoint `GET api/v1/faq` to retrieve the FAQs.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Implement proper error handling for various scenarios (e.g., invalid query parameters).

### Testing
* Write integration tests for the end-to-end get FAQs flow.
* Test various scenarios:
  * Retrieving all FAQs.
  * Retrieving FAQs with pagination.
