### ISSUE TITLE
FEAT: Super admin add regions

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#213]
## Description
Develop an API endpoint to create a new region entry with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/regions`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to create a new region.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
      "name": "Africa1",
      "code": "Af1"
  }
```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Region added successfully"
}
```

_Unsuccessful Response:_
* If the region already exists:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

_Validation Error Response:_
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {
        "Region.Code": "Code is a required field"
    }
}
 ```

### Purpose
Provides a backend service that allows authorized users to create a new region entry.

### Requirements
* Develop server-side logic to handle the creation of a new region.
* Ensure only users with appropriate permissions can create a new region.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows creation of a new region with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/regions` to create a new region.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Ensure the user has the proper permissions to create the region.
* [ ] Implement proper error handling for various scenarios (region exists, unauthorized access, etc.).
* [ ] Write integration tests for creating the region.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end create region flow.
* Test various scenarios:
  * Creating a new region with valid data.
  * Attempting to create a region with a duplicate name or code.
  * Attempting to create a region without authentication.
