### ISSUE TITLE
FEAT: Super admin add timezone

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#214]
## Description
Develop an API endpoint to create a new timezone entry with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/timezones`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to create a new timezone.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
  "identifier": "EST1",
  "offset": "+001"
}

```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Timezone added successfully"
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

_Validation Error Response:_
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
 ```

### Purpose
Provides a backend service that allows authorized users to create a new timezone entry.

### Requirements
* Develop server-side logic to handle the creation of a new timezone.
* Ensure only users with appropriate permissions can create a new timezone.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows creation of a new timezone with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/timezones` to create a new timezone.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Ensure the user has the proper permissions to create the timezone.
* [ ] Implement proper error handling for various scenarios (timezone exists, unauthorized access, etc.).
* [ ] Write integration tests for creating the timezone.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end create timezone flow.
* Test various scenarios:
  * Creating a new timezone with valid data.
  * Attempting to create a timezone with a duplicate name.
  * Attempting to create a timezone without authentication.
