### ISSUE TITLE
FEAT: Super admin add languages

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#215]
## Description
Develop an API endpoint to create a new language entry with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/languages`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to create a new language.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
  "name": "Spanish",
  "code": "sp"
}

```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Language added successfully"
}
```

_Unsuccessful Response:_
* If the language already exists:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

_Validation Error Response:_
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
 ```

### Purpose
Provides a backend service that allows authorized users to create a new language entry.

### Requirements
* Develop server-side logic to handle the creation of a new language.
* Ensure only users with appropriate permissions can create a new language.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows creation of a new language with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/languages` to create a new language.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Ensure the user has the proper permissions to create the language.
* [ ] Implement proper error handling for various scenarios (language exists, unauthorized access, etc.).
* [ ] Write integration tests for creating the language.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end create language flow.
* Test various scenarios:
  * Creating a new language with valid data.
  * Attempting to create a language with a duplicate name.
  * Attempting to create a language without authentication.
