### ISSUE TITLE
FEAT: Get all timezones

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#228]
## Description
Develop an API endpoint to retrieve a list of all timezones with appropriate validation and authentication.

#### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/timezones`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of timezones.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "retrieved successfully",
    "data": [
        {
            "id": "timezone-id-1",
            "identifier": "UTC+01:00",
            "offset": "+01:00"
        },
        {
            "id": "timezone-id-2",
            "identifier": "UTC-05:00",
            "offset": "-05:00"
        }
    ]
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve a list of all timezones.

### Requirements
* Develop server-side logic to handle the retrieval of all timezones.
* Ensure only users with appropriate permissions can retrieve the timezones.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of all timezones with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET /api/v1/timezones` to retrieve all timezones.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to retrieve the timezones.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for retrieving the timezones.
* [ ] Perform security testing to ensure only authorized users can access the data.
