### ISSUE TITLE
FEAT: Update users region, timezone and language.

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#230]
## Description
Develop an API endpoint to update a user's region entry with appropriate validation and authentication.

#### Acceptance Criteria
* The endpoint should be accessible at `PUT /api/v1/users/:user_id/regions`.
* The endpoint should accept HTTP PUT requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can update the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to update the user's region.

**Authorization: Bearer `<token>`**

#### Request
**Request Body:**
```json
{
    "region_id": "region-id",
    "timezone_id": "timezone-id",
    "language_id": "language-id"
}
```

#### Response
* On successful update, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "User info updated successfully"
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

_Validation Error Response:_
```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
}
```

### Purpose
Provides a backend service that allows authorized users to update a user's region entry.

### Requirements
* Develop server-side logic to handle the update of a user's region entry.
* Ensure only users with appropriate permissions can update the region entry.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows updating of a user's region entry with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `PUT /api/v1/users/:user_id/regions` to update a user's region entry.
* [ ] Implement server-side logic to handle successful and failed update requests.
* [ ] Ensure the user has the proper permissions to update the region entry.
* [ ] Implement proper error handling for various scenarios (validation failed, unauthorized access, etc.).
* [ ] Write integration tests for updating the user's region entry.
* [ ] Perform security testing to ensure only authorized users can access the data.
