### ISSUE TITLE
FEAT: Retrieve user region data

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#233]
## Description

Implement an API endpoint to retrieve the region information associated with a specific user.

### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/users/{user_id}/regions`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The response should return the region details for the specified user.

Authorization: Bearer `<token>`

#### Request
* **Method**: GET
* **URL**: `/api/v1/users/{user_id}/regions`
* **Headers**:
  ```json
  {
      "Authorization": "Bearer <token>"
  }
  ```

#### Response
* On successful retrieval, the API should return a 200 OK status code with the user region details.

**Response Body:**
```json
{
    "status": "success",
    "status_code": 200,
    "message": "User region retrieved successfully",
    "data": {
        "id": "019109d8-a5a6-7f4d-a3ec-ee3bd0383ee5",
        "user_id": "019109d8-a5a6-7f47-8cc5-d9b3f62293f8",
        "region_id": "019109d8-a5a6-7f4e-84a2-9e9f0eed380b",
        "timezone_id": "019109d8-a5a6-7f50-a8b4-47512d0150c9",
        "language_id": "019109d8-a5a6-7f4f-8824-0daa5e00a9bd",
        "created_at": "2024-07-31T18:31:18.832037+01:00",
        "updated_at": "2024-07-31T18:31:18.832037+01:00"
    }
}
```

* **Unsuccessful Response:**
  * If the user ID is invalid or not found:
    ```json
    {
        "status": "error",
        "status_code": 404,
        "message": "User not found"
    }
    ```

  * If the request is unauthorized:
    ```json
    {
        "status": "error",
        "status_code": 401,
        "message": "invalid token"
    }
    ```

### Purpose
Provides a backend service that allows authorized users to retrieve region information associated with a specific user.

### Requirements
* Develop server-side logic to handle retrieval of user region information.
* Ensure only users with appropriate permissions can access the user region data.
* Implement proper error handling for various scenarios (user not found, unauthorized access, etc.).

### Expected Outcome
* API endpoint allows retrieval of user region details with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET /api/v1/users/{user_id}/regions` to retrieve user region data.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the data.
* [ ] Implement proper error handling for various scenarios (user not found, unauthorized access).
* [ ] Write integration tests for the endpoint.
* [ ] Perform security testing to ensure only authorized users can access the data.
