### ISSUE TITLE
FEAT: Create roles in organisation

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#235]
## Description
Develop an API endpoint to create a new organization role with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/organizations/:org_id/roles`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to create a new role.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
    "name": "Admin Role",
    "description": "Role with full administrative privileges"
  }
  ```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Org role created successfully"
}
```

_Unsuccessful Response:_
* If the role creation fails due to a conflict or other issue:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
 ```

_Validation Error Response:_
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
 ```

### Purpose
Provides a backend service that allows authorized users to create a new role within an organization.

### Requirements
* Develop server-side logic to handle the creation of a new role.
* Ensure only users with appropriate permissions (e.g., organization owner) can create a new role.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows the creation of a new organization role with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/organizations/:org_id/roles` to create a new role.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Ensure the user has the proper permissions (e.g., organization owner) to create the role.
* [ ] Implement proper error handling for various scenarios (role exists, unauthorized access, etc.).
* [ ] Write integration tests for creating the role.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end create role flow.
* Test various scenarios:
  * Creating a new role with valid data.
  * Attempting to create a role with duplicate or invalid data.
  * Attempting to create a role without proper authentication.
