### ISSUE TITLE
FEAT: Get all roles in an organisation

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#236]
## Description
Develop an API endpoint to retrieve a list of roles for a specific organization with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/organizations/:org_id/roles`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request should return a list of roles associated with the specified organization.

Authorization: Bearer `<token>`

#### Request
**Request URL:**
```
GET /api/v1/organizations/:org_id/roles
```

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of roles.

```json
{
    "status": "success",
    "status_code": 200,
    "data": [
        {
            "id": "role_id_1",
            "name": "Admin Role",
            "description": "Role with full administrative privileges"
        },
        {
            "id": "role_id_2",
            "name": "User Role",
            "description": "Role with basic user privileges"
        }
    ]
}
```

_Unsuccessful Response:_
* If the organization does not exist or an error occurs:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
 ```

_Forbidden Access Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "Not authorized to access this organization"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve a list of roles within a specific organization.

### Requirements
* Develop server-side logic to handle retrieval of roles.
* Ensure only users with appropriate permissions (e.g., organization owner, admin) can access the roles.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of a list of roles with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET /api/v1/organizations/:org_id/roles` to retrieve roles.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the roles.
* [ ] Implement proper error handling for various scenarios (organization not found, unauthorized access, etc.).
* [ ] Write integration tests for retrieving the roles.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end retrieval of roles.
* Test various scenarios:
  * Retrieving roles for an existing organization with valid data.
  * Attempting to retrieve roles for a non-existent organization.
  * Attempting to retrieve roles without proper authentication.
  * Attempting to retrieve roles without proper authorization.
