### ISSUE TITLE
FEAT: Get specific roles permissions for an organisation

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#237]
## Description
Develop an API endpoint to retrieve details of a specific role within a specific organization with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/organizations/:org_id/roles/:role_id`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request should return details of the specified role within the specified organization.

Authorization: Bearer `<token>`

#### Request
**Request URL:**
```
GET /api/v1/organizations/:org_id/roles/:role_id
```

#### Response
* On successful retrieval, the API should return a 200 OK status code and the details of the role.

```json
{
    "status": "success",
    "status_code": 200,
    "data": {
        "id": "role_id",
        "name": "Admin Role",
        "description": "Role with full administrative privileges",
           "permissions": {
            "id": "string",
            "category": "string",
            "permission_list": { "can_view_transactions": boolean, "can_view_refunds": boolean, "can_edit_transactions": boolean }
        }

    }
}
```

_Unsuccessful Response:_
* If the role does not exist or an error occurs:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Role not found"
}
```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
 ```

_Forbidden Access Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "Not authorized to access this role"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve detailed information about a specific role within an organization.

### Requirements
* Develop server-side logic to handle retrieval of role details.
* Ensure only users with appropriate permissions (e.g., organization owner, admin) can access the role details.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of details of a specific role with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET /api/v1/organizations/:org_id/roles/:role_id` to retrieve role details.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the role details.
* [ ] Implement proper error handling for various scenarios (role not found, unauthorized access, etc.).
* [ ] Write integration tests for retrieving role details.
* [ ] Perform security testing to ensure only authorized users can access the role details.

### Testing
* Write integration tests for the end-to-end retrieval of role details.
* Test various scenarios:
  * Retrieving role details for an existing role with valid data.
  * Attempting to retrieve details for a non-existent role.
  * Attempting to retrieve role details without proper authorization.
