### ISSUE TITLE
FEAT: Delete an organisation role

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#238]
## Description
Develop an API endpoint to delete a specific role within a specific organization with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `DELETE /api/v1/organizations/:org_id/roles/:role_id`.
* The endpoint should accept HTTP DELETE requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request should remove the specified role from the organization.

Authorization: Bearer `<token>`

#### Request
**Request URL:**
```
DELETE /api/v1/organizations/:org_id/roles/:role_id
```

#### Response
* On successful deletion, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Role deleted successfully"
}
```

_Unsuccessful Response:_
* If the role does not exist or an error occurs:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Role not found"
}
```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
 ```

_Forbidden Access Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "Not authorized to delete this role"
}
```

### Purpose
Provides a backend service that allows authorized users to delete a specific role within an organization.

### Requirements
* Develop server-side logic to handle deletion of role.
* Ensure only users with appropriate permissions (e.g., organization owner, admin) can delete the role.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows deletion of a specific role with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `DELETE /api/v1/organizations/:org_id/roles/:role_id` to delete a role.
* [ ] Implement server-side logic to handle successful and failed deletion requests.
* [ ] Ensure the user has the proper permissions to delete the role.
* [ ] Implement proper error handling for various scenarios (role not found, unauthorized access, etc.).
* [ ] Write integration tests for deleting a role.
* [ ] Perform security testing to ensure only authorized users can delete the role.

### Testing
* Write integration tests for the end-to-end deletion of a role.
* Test various scenarios:
  * Deleting an existing role with valid data.
  * Attempting to delete a non-existent role.
  * Attempting to delete a role without proper authorization.
