### ISSUE TITLE
FEAT: Update organisation role

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#239]
## Description
Develop an API endpoint to update an existing organization role with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/organizations/:org_id/roles/:role_id`.
* The endpoint should accept HTTP PATCH requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary fields to update the role, including `name` and `description`.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
    "name": "Updated Role Name",
    "description": "Updated role description"
  }
  ```

#### Response
* On successful update, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Org role updated successfully"
}
```

_Unsuccessful Response:_
* If the role does not exist:
```json
{
    "status": "error",
    "status_code": 404,
    "message": "Role not found"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

_Validation Error Response:_
```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
```

### Purpose
Provides a backend service that allows authorized users to update details of an existing organization role.

### Requirements
* Develop server-side logic to handle the update of an existing role.
* Ensure only users with appropriate permissions can update the role.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows updating of an existing organization role with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `PATCH /api/v1/organizations/:org_id/roles/:role_id` to update an organization role.
* [ ] Implement server-side logic to handle successful and failed update requests.
* [ ] Ensure the user has the proper permissions to update the role.
* [ ] Implement proper error handling for various scenarios (role not found, unauthorized access, etc.).
* [ ] Write integration tests for updating the role.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end update role flow.
* Test various scenarios:
  * Updating a role with valid data.
  * Attempting to update a role that does not exist.
  * Attempting to update a role without authentication.
  * Attempting to update a role with invalid data.
