### ISSUE TITLE
FEAT: Update organisation permissions

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#240]
## Description
Develop an API endpoint to update or add the permissions of an existing organization role with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/organizations/:org_id/roles/:role_id/permissions`.
* The endpoint should accept HTTP PATCH requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to update permissions, including `category` and `permission_list`.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
    "category": "market",
    "permission_list": {
      "can_view_transactions": true,
      "can_view_refunds": false,
      "can_edit_transactions": true
    }
  }
  ```

#### Response
* On successful update, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Org role permissions updated successfully"
}
```

_Unsuccessful Response:_
* If the role does not exist:
```json
{
    "status": "error",
    "status_code": 404,
    "message": "Role not found"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

_Validation Error Response:_
```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
```

### Purpose
Provides a backend service that allows authorized users to update permissions associated with an existing organization role.

### Requirements
* Develop server-side logic to handle updating of permissions for an existing role.
* Ensure only users with appropriate permissions can update the role's permissions.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows updating of permissions for an existing organization role with appropriate authentication and error handling.

### Tasks
* [x] Create an endpoint `PATCH /api/v1/organizations/:org_id/roles/:role_id/permissions` to update permissions of an organization role.
* [x] Implement server-side logic to handle successful and failed update requests.
* [x] Ensure the user has the proper permissions to update the role's permissions.
* [x] Implement proper error handling for various scenarios (role not found, unauthorized access, etc.).
* [x] Write integration tests for updating role permissions.
* [x] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end update permissions flow.
* Test various scenarios:
  * Updating permissions with valid data.
  * Attempting to update permissions for a role that does not exist.
  * Attempting to update permissions without authentication.
  * Attempting to update permissions with invalid data.
