### ISSUE TITLE
FEAT: Implement Template Creation - POST

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#242]
## Description
Develop an API endpoint to create and store email templates in the database.

#### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/template`.
* The endpoint should accept HTTP POST requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can create email templates.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Request
* The request body should include the name and body of the email template in JSON format.

```json
{
    "name": "send_otp",
    "body": "this is the email body"
}
```

#### Response

**Success (201 Created)**

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Template created successfully",
    "data": {
        "id": "01910c39-01e0-73b7-bed9-d326a6ea5197",
        "name": "send_otp",
        "body": "this is the email body",
        "created_at": "2024-08-01T05:35:48.3211659+01:00",
        "updated_at": "2024-08-01T05:35:48.3211659+01:00"
    }
}
```

**Validation Error (422 Unprocessable Entity)**

```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {
        "TemplateRequest.Body": "Body is a required field"
    }
}
```

**Authorization Error (401 Unauthorized)**

```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

### Purpose
Provides a backend service that allows authorized users to create and store email templates in the database.

### Requirements
* Develop server-side logic to handle the creation and storage of email templates.
* Ensure only users with appropriate permissions can create email templates.
* Implement proper error handling and status code responses for validation and authorization errors.

### Expected Outcome
* API endpoint allows creation and storage of email templates with appropriate authentication and error handling.

### Tasks
* [X] Create an endpoint `POST /api/v1/template` to create email templates.
* [X] Implement server-side logic to handle successful and failed creation requests.
* [X] Ensure the user has the proper permissions to create email templates.
* [X] Implement proper error handling for various scenarios (validation errors, unauthorized access, etc.).
* [X] Write integration tests for creating email templates.
* [X] Perform security testing to ensure only authorized users can create email templates.
