### ISSUE TITLE
FEAT: Get All Email Templates

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#243]
## Description
Develop an API endpoint to retrieve all email templates stored in the database.

#### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/template`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can retrieve email templates.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Response

**Success (200 OK)**

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Templates Successfully retrieved",
    "data": [
        {
            "id": "01910b38-22db-79a1-a766-26b69757e3d2",
            "name": "template_name",
            "body": "this is the email body",
            "created_at": "2024-08-01T00:55:14.011782+01:00",
            "updated_at": "2024-08-01T00:55:14.011782+01:00"
        },
        {
            "id": "01910b39-22db-79a1-a766-26b69757e3d3",
            "name": "another_template_name",
            "body": "another email body",
            "created_at": "2024-08-01T01:55:14.011782+01:00",
            "updated_at": "2024-08-01T01:55:14.011782+01:00"
        }
    ]
}
```

**Authorization Error (401 Unauthorized)**

```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve all email templates stored in the database.

### Requirements
* Develop server-side logic to handle the retrieval of all email templates.
* Ensure only users with appropriate permissions can retrieve email templates.
* Implement proper error handling and status code responses for unauthorized access.

### Expected Outcome
* API endpoint allows retrieval of all email templates with appropriate authentication and error handling.

### Tasks
* [X] Create an endpoint `GET /api/v1/template` to retrieve all email templates.
* [X] Implement server-side logic to handle successful and failed retrieval requests.
* [X] Ensure the user has the proper permissions to retrieve email templates.
* [X] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [X] Write integration tests for retrieving email templates.
* [X] Perform security testing to ensure only authorized users can retrieve email templates.
