### ISSUE TITLE
FEAT: Get Email Template by ID

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#244]
## Description
Develop an API endpoint to retrieve a specific email template by its ID.

#### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/template/:id`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can retrieve an email template by its ID.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Response

**Success (200 OK)**

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Template Successfully retrieved",
    "data": {
        "id": "01910b26-4508-7e1b-8855-15aeb15133aa",
        "name": "send_invitation",
        "body": "<!DOCTYPE html>\r\n<html>\r\n  <body\r\n  </body>\r\n</html>",
        "created_at": "2024-08-01T02:00:14.011782+01:00",
        "updated_at": "2024-08-01T02:00:14.011782+01:00"
    }
}
```

**Authorization Error (401 Unauthorized)**

```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

**Not Found Error (404 Not Found)**

```json
{
    "status": "error",
    "status_code": 404,
    "message": "Template not found"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve a specific email template by its ID.

### Requirements
* Develop server-side logic to handle the retrieval of a specific email template by its ID.
* Ensure only users with appropriate permissions can retrieve the email template.
* Implement proper error handling and status code responses for unauthorized access and not found errors.

### Expected Outcome
* API endpoint allows retrieval of a specific email template by its ID with appropriate authentication and error handling.

### Tasks
* [X] Create an endpoint `GET /api/v1/template/:id` to retrieve an email template by its ID.
* [X] Implement server-side logic to handle successful and failed retrieval requests.
* [X] Ensure the user has the proper permissions to retrieve the email template.
* [X] Implement proper error handling for various scenarios (unauthorized access, not found errors, etc.).
* [X] Write integration tests for retrieving an email template by its ID.
* [X] Perform security testing to ensure only authorized users can retrieve the email template.
