### ISSUE TITLE
FEAT: Update Email Template by ID

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#245]
## Description
Develop an API endpoint to update a specific email template by its ID.

#### Acceptance Criteria
* The endpoint should be accessible at `PUT /api/v1/template/:id`.
* The endpoint should accept HTTP PUT requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can update an email template by its ID.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Request

**Headers**

```
Authorization: Bearer <token>
Content-Type: application/json
```

**Body**

```json
{
    "name": "updated_template_name",
    "body": "<!DOCTYPE html>\r\n<html>\r\n  <body>\r\n  Updated template body\r\n  </body>\r\n</html>"
}
```

#### Response

**Success (200 OK)**

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Template Successfully updated",
    "data": {
        "id": "01910b26-4508-7e1b-8855-15aeb15133aa",
        "name": "updated_template_name",
        "body": "<!DOCTYPE html>\r\n<html>\r\n  <body>\r\n  Updated template body\r\n  </body>\r\n</html>",
        "created_at": "2024-08-01T02:00:14.011782+01:00",
        "updated_at": "2024-08-01T03:00:14.011782+01:00"
    }
}
```

**Validation Error (422 Unprocessable Entity)**

```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {
        "TemplateRequest.Body": "Body is a required field"
    }
}
```

**Authorization Error (401 Unauthorized)**

```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

**Not Found Error (404 Not Found)**

```json
{
    "status": "error",
    "status_code": 404,
    "message": "Template not found"
}
```

### Purpose
Provides a backend service that allows authorized users to update a specific email template by its ID.

### Requirements
* Develop server-side logic to handle the update of a specific email template by its ID.
* Ensure only users with appropriate permissions can update the email template.
* Implement proper error handling and status code responses for validation errors, unauthorized access, and not found errors.

### Expected Outcome
* API endpoint allows updating a specific email template by its ID with appropriate authentication and error handling.

### Tasks
* [X] Create an endpoint `PUT /api/v1/template/:id` to update an email template by its ID.
* [X] Implement server-side logic to handle successful and failed update requests.
* [X] Ensure the user has the proper permissions to update the email template.
* [X] Implement proper error handling for various scenarios (validation errors, unauthorized access, not found errors, etc.).
* [X] Write integration tests for updating an email template by its ID.
* [X] Perform security testing to ensure only authorized users can update the email template.

---
