### ISSUE TITLE
FEAT: Delete Email Template by ID

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#246]
## Description
Develop an API endpoint to delete a specific email template by its ID.

#### Acceptance Criteria
* The endpoint should be accessible at `DELETE /api/v1/template/:id`.
* The endpoint should accept HTTP DELETE requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can delete an email template by its ID.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

**Authorization: Bearer `<token>`**

#### Response

**Success (200 OK)**

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Template Successfully deleted"
}
```

**Authorization Error (401 Unauthorized)**

```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

**Not Found Error (404 Not Found)**

```json
{
    "status": "error",
    "status_code": 404,
    "message": "Template not found"
}
```

### Purpose
Provides a backend service that allows authorized users to delete a specific email template by its ID.

### Requirements
* Develop server-side logic to handle the deletion of a specific email template by its ID.
* Ensure only users with appropriate permissions can delete the email template.
* Implement proper error handling and status code responses for unauthorized access and not found errors.

### Expected Outcome
* API endpoint allows deleting a specific email template by its ID with appropriate authentication and error handling.

### Tasks
* [X] Create an endpoint `DELETE /api/v1/template/:id` to delete an email template by its ID.
* [X] Implement server-side logic to handle successful and failed deletion requests.
* [X] Ensure the user has the proper permissions to delete the email template.
* [X] Implement proper error handling for various scenarios (unauthorized access, not found errors, etc.).
* [X] Write integration tests for deleting an email template by its ID.
* [X] Perform security testing to ensure only authorized users can delete the email template.
