### ISSUE TITLE
FEAT: Implement Update Notification Settings Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#254]
## Description
Develop an API endpoint to update a user's notification settings. The endpoint should accept PATCH requests and update the notification preferences based on the provided data.

#### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/notification-settings`.
* The endpoint should accept HTTP PATCH requests with a request body containing any of the following fields:
  ```json
  {
    "mobile_push_notifications": "boolean",
    "email_notification_activity_in_workspace": "boolean",
    "email_notification_always_send_email_notifications": "boolean",
    "email_notification_email_digest": "boolean",
    "email_notification_announcement_and_update_emails": "boolean",
    "slack_notifications_activity_on_your_workspace": "boolean",
    "slack_notifications_always_send_email_notifications": "boolean",
    "slack_notifications_announcement_and_update_emails": "boolean"
  }
  ```
* The endpoint should return a success response with a 200 OK status code and only the changed data.

**Authorization: Bearer `<token>`**

#### Response
* On successful update, the API should return a 200 OK status code and the updated notification settings.

```json
{
    "status": "success",
    "message": "Notification preferences retrieved successfully",
    "status_code": 200,
    "data": {
        "email_notification_activity_in_workspace": "boolean",
        "email_notification_always_send_email_notifications": "boolean",
        "email_notification_email_digest": "boolean",
        "email_notification_announcement_and_update_emails": "boolean",
        "slack_notifications_activity_on_your_workspace": "boolean",
        "slack_notifications_always_send_email_notifications": "boolean",
        "slack_notifications_announcement_and_update_emails": "boolean"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid input"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized"
}
```

### Purpose
Provides an endpoint to update notification settings for a user.

### Requirements
* Develop server-side logic to handle the update of notification settings.
* Ensure proper validation and error handling.
* Implement authentication to secure the endpoint.

### Expected Outcome
* API endpoint allows users to update their notification settings with proper validation and error handling.

### Tasks
* [ ] Create an endpoint `PATCH /api/v1/notification-settings` for updating notification settings.
* [ ] Implement logic to handle successful and failed updates.
* [ ] Ensure proper validation and authorization.
* [ ] Write tests for the endpoint.

---
