### ISSUE TITLE
FEAT: Create Notification Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#255]
## Description
Develop an API endpoint to create a new notification. The endpoint should accept POST requests and store the notification message.

#### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/notifications`.
* The endpoint should accept HTTP POST requests with a request body containing the notification message.
  ```json
  {
    "message": "string"
  }
  ```
* The endpoint should return a success response with a 201 Created status code.

**Authorization: Bearer `<token>`**

#### Response
* On successful creation, the API should return a 201 Created status code and the newly created notification.

```json
{
    "status": "success",
    "message": "Notification created successfully",
    "status_code": 201,
    "data": {
        "notifications": [
            {
                "notification_id": "uuid",
                "user_id": "uuid",
                "message": "string",
                "is_read": false,
                "created_at": "datetime (ISO 8601)"
            }
        ]
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid request"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized request"
}
```

### Purpose
Provides an endpoint to create a new notification for a user.

### Requirements
* Develop server-side logic to handle the creation of notifications.
* Ensure proper validation and error handling.
* Implement authentication to secure the endpoint.

### Expected Outcome
* API endpoint allows users to create notifications with proper validation and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/notifications` for creating notifications.
* [ ] Implement logic to handle successful and failed creation requests.
* [ ] Ensure proper validation and authorization.
* [ ] Write tests for the endpoint.

---
