### ISSUE TITLE
FEAT: Retrieve User’s Notifications Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#256]
## Description
Develop an API endpoint to retrieve a user's notifications, including both read and unread notifications.

#### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/notifications`.
* The endpoint should accept HTTP GET requests and return the user's notifications.

**Authorization: Bearer `<token>`**

#### Response
* On successful retrieval, the API should return a 200 OK status code and the user's notifications, including a count of total and unread notifications.

```json
{
    "status": "success",
    "message": "Notifications retrieved successfully",
    "status_code": 200,
    "data": {
        "total_notification_count": "int",
        "total_unread_notification_count": "int",
        "notifications": [
            {
                "notification_id": "uuid",
                "is_read": false,
                "message": "string",
                "created_at": "datetime (ISO 8601)"
            }
        ]
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid request"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized request"
}
```

### Purpose
Provides an endpoint to retrieve all notifications for a user.

### Requirements
* Develop server-side logic to handle the retrieval of notifications.
* Ensure proper authentication and error handling.

### Expected Outcome
* API endpoint allows users to retrieve their notifications.

### Tasks
* [ ] Create an endpoint `GET /api/v1/notifications` for retrieving notifications.
* [ ] Implement logic to handle successful and failed retrieval requests.
* [ ] Ensure proper authentication and authorization.
* [ ] Write tests for the endpoint.

---
