### ISSUE TITLE
FEAT: Retrieve User’s Unread Notifications Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#257]
## Description
Develop an API endpoint to retrieve only unread notifications for a user. The endpoint should accept a query parameter to filter unread notifications.

#### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/notifications`.
* The endpoint should accept the query parameter `is_read=false` and return only unread notifications.

**Authorization: Bearer `<token>`**

#### Response
* On successful retrieval, the API should return a 200 OK status code and the user's unread notifications, including a count of total and unread notifications.

```json
{
    "status": "success",
    "message": "Unread notifications retrieved successfully",
    "status_code": 200,
    "data": {
        "total_notification_count": "int",
        "total_unread_notification_count": "int",
        "notifications": [
            {
                "notification_id": "uuid",
                "is_read": false,
                "message": "string",
                "created_at": "datetime (ISO 8601)"
            }
        ]
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 

400,
    "message": "Invalid request"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized request"
}
```

### Purpose
Provides an endpoint to retrieve only unread notifications for a user.

### Requirements
* Develop server-side logic to handle the retrieval of unread notifications.
* Ensure proper authentication and error handling.

### Expected Outcome
* API endpoint allows users to retrieve their unread notifications.

### Tasks
* [ ] Create an endpoint `GET /api/v1/notifications` with query parameter `is_read=false` for retrieving unread notifications.
* [ ] Implement logic to handle successful and failed retrieval requests.
* [ ] Ensure proper authentication and authorization.
* [ ] Write tests for the endpoint.

---
