### ISSUE TITLE
FEAT: Update Notification Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#258]
## Description
Develop an API endpoint to update a specific notification . The endpoint should accept a PATCH request with the notification ID and update it.

#### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/notifications/{notification_id}`.
* The endpoint should accept HTTP PATCH requests with a request body containing:
  ```json
  {
    "is_read": true
  }
  ```
* The endpoint should return a success response with a 200 OK status code.

**Authorization: Bearer `<token>`**

#### Response
* On successful update, the API should return a 200 OK status code and the updated notification.

```json
{
    "status": "success",
    "message": "Notification updated successfully",
    "status_code": 200,
    "data": {
        "notification_id": "uuid",
        "is_read": true,
        "updated_at": "datetime (ISO 8601)"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid request"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized request"
}
```

### Purpose
Provides an endpoint to update a specific notification .

### Requirements
* Develop server-side logic to update a notification.
* Ensure proper validation and error handling.
* Implement authentication to secure the endpoint.

### Expected Outcome
* API endpoint allows users to update an individual notification.

### Tasks
* [ ] Create an endpoint `PATCH /api/v1/notifications/{notification_id}`.
* [ ] Implement logic to handle successful and failed update requests.
* [ ] Ensure proper validation and authorization.
* [ ] Write tests for the endpoint.

---
