### ISSUE TITLE
FEAT: Delete Notification Endpoint

### ISSUE THREAD

**Issue by Micah-Shallom** [hngprojects/hng_boilerplate_golang_web#259]
## Description
Develop an API endpoint to delete a notification for a user. The endpoint should accept a DELETE request and delete the notification

#### Acceptance Criteria
* The endpoint should be accessible at `DELETE /api/v1/notifications/notification_id`.
* The endpoint should accept HTTP DELETE requests and delete.
* The endpoint should return a success response with a 200 OK status code.

**Authorization: Bearer `<token>`**

#### Response
* On successful update, the API should return a 200 OK status code and an empty list of notifications.

```json
{
    "status": "success",
    "message": "Notifications cleared successfully",
    "status_code": 200,
    "data": {
        "notifications": []
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid request"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Unauthorized request"
}
```

### Requirements
* Develop server-side logic to handle the marking of all notifications as read.
* Ensure proper validation and error handling.
* Implement authentication to secure the endpoint.

### Expected Outcome
* API endpoint allows users to delete notification.

### Tasks
* [ ] Create an endpoint `DELETE /api/v1/notifications`.
* [ ] Implement logic to handle successful and failed update requests.
* [ ] Ensure proper validation and authorization.
* [ ] Write tests for the endpoint.
