### ISSUE TITLE
FEAT: Get all messages from contact us page with page and limit filter

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#276]
## Description
Develop an API endpoint to retrieve all contact records with appropriate authentication and authorization.

### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/contact?page=1&limit=10`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with the SuperAdmin role can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Response
* On successful retrieval, the API should return a 200 OK status code and a list of contact records.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Messages retrieved successfully",
    "data": [
        {
            "id": "uuid1",
            "name": "John Doe",
            "email": "johndoe@example.com",
            "subject": "Inquiry",
            "message": "I would like to know more about your services."
        }
    ]
}
```

_Unsuccessful Response:_
* If the token is invalid:
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "role not authorized!"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve all contact records.

### Requirements
* Develop server-side logic to handle retrieval of all contact records.
* Ensure only users with the SuperAdmin role can access the contact records.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows authorized users with the SuperAdmin role to retrieve all contact records.

### Tasks
* [ ] Create an endpoint `GET /api/v1/contact?page=1&limit=10` to retrieve all contact records.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper role (SuperAdmin) to access the contact records.
* [ ] Implement proper error handling for various scenarios (unauthorized access, invalid token, etc.).
* [ ] Write integration tests for retrieving contact records.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end retrieval flow.
* Test various scenarios:
  * Retrieving all contact records with valid data.
  * Attempting to retrieve records with invalid or expired tokens.
  * Attempting to retrieve records without proper authorization.
