### ISSUE TITLE
FEAT: Get one message with id from contact us page

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#277]
## Description
Develop an API endpoint to retrieve a contact record by ID with appropriate authentication and authorization.

### Acceptance Criteria
* The endpoint should be accessible at `GET /api/v1/contact/id/:id`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with the SuperAdmin role can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Response
* On successful retrieval, the API should return a 200 OK status code and the requested contact record.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Contact record retrieved successfully",
    "data": {
        "id": "uuid1",
        "name": "John Doe",
        "email": "johndoe@example.com",
        "subject": "Inquiry",
        "message": "I would like to know more about your services."
    }
}
```

_Unsuccessful Response:_
* If the token is invalid:
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "role not authorized!"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve a specific contact record by ID.

### Requirements
* Develop server-side logic to handle retrieval of a contact record by ID.
* Ensure only users with the SuperAdmin role can access the contact record.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows authorized users with the SuperAdmin role to retrieve a contact record by ID.

### Tasks
* [ ] Create an endpoint `GET /api/v1/contact/id/:id` to retrieve a contact record by ID.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper role (SuperAdmin) to access the contact record.
* [ ] Implement proper error handling for various scenarios (unauthorized access, invalid token, record not found, etc.).
* [ ] Write integration tests for retrieving a contact record by ID.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end retrieval by ID flow.
* Test various scenarios:
  * Retrieving a contact record with a valid ID and token.
  * Attempting to retrieve a record with an invalid or expired token.
  * Attempting to retrieve a record with insufficient authorization.
