### ISSUE TITLE
FEAT: Delete a message gotten from contact us page

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#279]
## Description
Develop an API endpoint to delete a contact record by ID with appropriate authentication and authorization.

### Acceptance Criteria
* The endpoint should be accessible at `DELETE /api/v1/contact/:id`.
* The endpoint should accept HTTP DELETE requests.
* The endpoint should be secured to ensure that only authenticated users with the SuperAdmin role can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Response
* On successful deletion, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Contact record deleted successfully"
}
```

_Unsuccessful Response:_
* If id is not found:
```json
{
    "status": "error",
    "status_code": 404,
    "message": "doesn't exist!"
}
```
* If the token is invalid:
```json
{
    "status": "error",
    "status_code": 401,
    "message": "Token is invalid!"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 403,
    "message": "role not authorized!"
}
```

### Purpose
Provides a backend service that allows authorized users to delete a specific contact record by ID.

### Requirements
* Develop server-side logic to handle deletion of a contact record by ID.
* Ensure only users with the SuperAdmin role can delete the contact record.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows authorized users with the SuperAdmin role to delete a contact record by ID.

### Tasks
* [ ] Create an endpoint `DELETE /api/v1/contact/:id` to delete a contact record by ID.
* [ ] Implement server-side logic to handle successful and failed deletion requests.
* [ ] Ensure the user has the proper role (SuperAdmin) to delete the contact record.
* [ ] Implement proper error handling for various scenarios (unauthorized access, invalid token, record not found, etc.).
* [ ] Write integration tests for deleting a contact record by ID.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end deletion flow.
* Test various scenarios:
  * Deleting a contact record with a valid ID and token.
  * Attempting to delete a record with an invalid or expired token.
  * Attempting to delete a record with insufficient authorization.
