### ISSUE TITLE
FEAT: Send a message from contact us page

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#280]
## Description
Develop an API endpoint to create a new contact record with appropriate validation.

### Acceptance Criteria
* The endpoint should be accessible at `POST /api/v1/contact`.
* The endpoint should accept HTTP POST requests.
* The request body should contain the necessary data to create a new contact record.

#### Request
**Request Body:**
```json
{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "subject": "</br><i>Inquiry about services3 with html",
    "message": "I would like to know more about your services3."
}
```

#### Response
* On successful creation, the API should return a 201 Created status code and a success message.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Contact Us record created successfully"
}
```

_Unsuccessful Response:_
* If the request body is missing required fields:
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Request body is invalid or missing fields"
}
```

_Validation Error Response:_
```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
```

### Purpose
Provides a backend service that allows users to send a message to the company.

### Requirements
* Develop server-side logic to handle the creation of a new contact record.
* Implement validation for required fields and proper error handling.

### Expected Outcome
* API endpoint allows authenticated users to create a new contact record with appropriate validation and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/contact` to create a new contact record.
* [ ] Implement server-side logic to handle successful and failed creation requests.
* [ ] Implement validation for required fields and handle errors appropriately.
* [ ] Write integration tests for creating a contact record.

### Testing
* Write integration tests for the end-to-end create contact record flow.
* Test various scenarios:
  * Creating a new contact record with valid data.
  * Attempting to create a record with missing or invalid data.
