### ISSUE TITLE
FEAT: Super admin update timezone 

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#287]
## Description
Develop an API endpoint to update an existing timezone entry with appropriate validation and authentication.

### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/timezones/:id`.
* The endpoint should accept HTTP PATCH requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.
* The request body should contain the necessary data to update an existing timezone.

Authorization: Bearer `<token>`

#### Request
**Request Body:**
  ```json
  {
    "timezone": "America/New_York",
    "gmtOffset": "-05:00",
    "description": "Eastern Standard Time"
  }
  ```

#### Response
* On successful update, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Timezone updated successfully"
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
 ```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
 ```

_Validation Error Response:_
 ```json
{
    "status": "error",
    "status_code": 422,
    "message": "Validation failed",
    "error": {}
}
 ```

### Purpose
Provides a backend service that allows authorized admin to update an existing timezone entry.

### Requirements
* Develop server-side logic to handle the updating of an existing timezone.
* Ensure only users with appropriate permissions can update the timezone.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows updating of an existing timezone with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `PATCH /api/v1/timezones/:id` to update an existing timezone.
* [ ] Implement server-side logic to handle successful and failed update requests.
* [ ] Ensure the user has the proper permissions to update the timezone.
* [ ] Implement proper error handling for various scenarios (timezone not found, unauthorized access, etc.).
* [ ] Write integration tests for updating the timezone.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end update timezone flow.
* Test various scenarios:
  * Updating an existing timezone with valid data.
  * Attempting to update a timezone with invalid data.
  * Attempting to update a timezone without authentication.
