### ISSUE TITLE
FEAT: Restore Deleted Email For Subscription

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#289]
## Description
Develop an API endpoint to restore a deleted newsletter subscription with proper authentication and validation.

### Acceptance Criteria
* The endpoint should be accessible at `PATCH /api/v1/newsletter-subscription/restore/:id`.
* The endpoint should accept HTTP PATCH requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Request
**Request Path:**
    "id": "0190ff8c-96d7-79e7-a13d-154449084572"

#### Response
* On successful restoration, the API should return a 200 OK status code and a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Newsletter subscription restored successfully"
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
 ```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

### Purpose
Provides a backend service that allows authorized users to restore a deleted newsletter subscription.

### Requirements
* Develop server-side logic to handle the restoration of a deleted newsletter subscription.
* Ensure only users with appropriate permissions can restore the subscription.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows restoration of a deleted newsletter subscription with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `PATCH /api/v1/newsletter-subscription/restore/:id` to restore a deleted newsletter subscription.
* [ ] Implement server-side logic to handle successful and failed restoration requests.
* [ ] Ensure the user has the proper permissions to restore the subscription.
* [ ] Implement proper error handling for various scenarios (subscription not found, unauthorized access, etc.).
* [ ] Write integration tests for restoring the subscription.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end restore subscription flow.
* Test various scenarios:
  * Restoring a deleted newsletter subscription with valid data.
  * Attempting to restore a non-existent subscription.
  * Attempting to restore a subscription without authentication.
