### ISSUE TITLE
[FEAT] Add 2-FACTOR-AUTHENTICATION

### ISSUE THREAD

**Issue by urizennnn** [hngprojects/hng_boilerplate_golang_web#296]
## Description
Develop API endpoints to enable and verify two-factor authentication (2FA) using TOTP. Ensure proper authentication, validation, and error handling.

### Acceptance Criteria
* The endpoint to enable 2FA should be accessible at `POST /api/v1/auth/2fa/enable`.
* The endpoint to verify 2FA should be accessible at `POST /api/v1/auth/2fa/verify`.
* Both endpoints should be secured to ensure only authenticated users can access them.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoints must include a valid authentication token in the Authorization header.

#### Request to Enable 2FA
* The request should be made by an already logged in user as the user id is gotten from the token.

#### Response for Successful Enablement
* On successful creation of the 2FA key, the API should return a 201 Created status code with the QR code and secret.

```json
{
    "status": "success",
    "status_code": 201,
    "message": "Key created successfully",
    "data": {
        "qr_code": "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEAAQMAAABmvDolAAAABlBMVEX///8AAABVwtN+AAADXElEQVR42uyYMY7rOBBEi1DAkDcwL2JI13JgQAIc+Fo0dBHqBgwZCKpFtezxzEYbrDUMhsGHvucJoNjd1cXG3/pb//caSM4sXB15n7dQr45At5DcmgF6wCdXAJeLX2OpIxnuXIr96SAg8p4cOQEYE1DhMqdhKVzbAuYcyAfLBQhcB4Z6docDGzA+MkkWT2YAjQGAn5eCkTnweaQ62x/58GHA0n4p9drHcP/28LMufhnQ6jJq98hWILwxk+mniHwY6KFKZB0fKkmyokcZ10hOfTPAkAvOrugrKN3QVxQ/Z9SX0n4ecDlwdUV7C0ynwAnRXvG3rSGgYMjwKyLGeaGKtHiF+4qjgB7WcTxT1APRpcg6qFq3ZoCBBcPC2m0RlzNChaN6E037jwFcNv2qXYphEnB1DPc1Fr+iGWAgp25TuMGKSGtJU5fxUvsDAMs0nZ3+e4706yARi/S31AzQx1BxCnooF23+RvVuBD5r8wBAHm+NJqSscJb/YTrHr47TAtAryrbnWC7nk7kt1m5hfQvIpwElOTP8LUVpl+V/GWelXDtAHwsQZd3ViXa3A59O+OqbBwCg2bvrIFvK4idH+Jn8yskGAJclF0FysbtB4RezPekowKydfk5qPcq0HsXTXF9DgCktOqoJyQ2qSIe3yTkCwDOIUlQ93B4sezRTO4B1Q1ViVAMP9Sq1Zw6v3n0IYE1Y8ZTs76+Yde/aARxDHTbUq74Cp52U/r/uFwcAlva6kG4wEfOTPGq3fcvJ3wcQcZEjtPHLGfo9clJ/fJuczwO8ryfYhd0zY9cHxbchQJvXP9fBDjDoaibJtdM8CDBrJ8pJxJ6OtMqjsh1AbrDLdu0qI7ewU1L78TgAlvbSLvgUC7oH7UjrmJoBBkIm0N+2GLieAvlQ7n0f1Hwc0D1rztpSNNdXr320I20KoNwgq03VZou7HCn5NV74PDDwFcRcPEkBQVf4OrYD2FRtKbCBnkwOHzQ3+LLuBwA2XbQ7sva2T8+KXvkxfvxlwCb/p+Apf6WvmEQq97rjgEi5YuuGWgri/tAYkFQXKeLSbUE3sjB9n2gdBKjbMIeq0CqIl/N7YNUEsIdbX8E7SU8V6erec5jPA8+099NAoMvBjMSYEP5VF78K/K2/9d/XPwEAAP//t6O0tRaI1+kAAAAASUVORK5CYII=",
        "secret": "CLRFZILMEJ7UC74ELOEG4R6W5AMLTHXM"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "User not found",
    "error": {}
}
```

#### Request to Verify 2FA
* The request body should include the  TOTP key and must be made by an authenticated user as the user id is gotten from there .

```json
{
    "key":"583104"
}
```

#### Response for Successful Verification
* On successful verification of the 2FA key, the API should return a 200 OK status code with a success message.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Key verified successfully",
    "data": {
        "message": "Key verified successfully"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "Invalid key",
    "error": {}
}
```

### Purpose
Provides backend services that allow users to enable and verify two-factor authentication (2FA) using TOTP for enhanced security.

### Requirements
* Develop server-side logic to generate and store TOTP secrets.
* Develop server-side logic to verify TOTP keys.
* Ensure only authenticated users can access the endpoints.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoints allow users to enable and verify 2FA with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `POST /api/v1/auth/2fa/enable` to enable 2FA.
* [ ] Create an endpoint `POST /api/v1/auth/2fa/verify` to verify 2FA.
* [ ] Implement server-side logic to handle the generation and storage of TOTP secrets.
* [ ] Implement server-side logic to handle the verification of TOTP keys.
* [ ] Ensure users are authenticated and authorized to access the endpoints.
* [ ] Implement proper error handling for various scenarios (e.g., user not found, invalid key).
* [ ] Write integration tests for enabling and verifying 2FA.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end 2FA enablement and verification flow.
* Test various scenarios:
  * Enabling 2FA with a valid user ID.
  * Verifying 2FA with a valid user ID and key.
  * Handling errors such as user not found and invalid key.
