### ISSUE TITLE
FEAT: Get user data privacy settings

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#308]
## Description
Develop an API endpoint to retrieve data privacy settings with proper authentication and validation.

### Acceptance Criteria

* The endpoint should be accessible at `GET /api/v1/users/{id}/data-privacy-settings`.
* The endpoint should accept HTTP GET requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can access the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Request
* No request body is required.
* The `id` parameter should be included in the URL path.

#### Response
* On successful retrieval, the API should return a 200 OK status code and the data privacy settings.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Data privacy settings retrieved successfully",
    "data": {
        "id": "0190ff8c-96d7-79e7-a13d-154449084572",
        "user_id": "12345678-1234-1234-1234-123456789012",
        "profile_visibility": false,
        "share_data_with_partners": false,
        "receive_email_updates": false,
        "enable_2fa": false,
        "use_data_encryption": false,
        "allow_analytics": false,
        "personalized_ads": false,
        "created_at": "2024-07-29T18:32:02.135934+01:00",
        "updated_at": "2024-07-30T18:32:02.135934+01:00"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

### Purpose
Provides a backend service that allows authorized users to retrieve data privacy settings with proper authentication and validation.

### Requirements
* Develop server-side logic to retrieve data privacy settings.
* Ensure only users with appropriate permissions can access the data.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows retrieval of data privacy settings with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `GET /api/v1/users/{id}/data-privacy-settings` to retrieve data privacy settings.
* [ ] Implement server-side logic to handle successful and failed retrieval requests.
* [ ] Ensure the user has the proper permissions to access the data.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for retrieving data privacy settings.
* [ ] Perform security testing to ensure only authorized users can access the data.

### Testing
* Write integration tests for the end-to-end retrieval of data privacy settings.
* Test various scenarios:
  * Retrieving data privacy settings.
  * Attempting to retrieve data privacy settings without authentication.
