### ISSUE TITLE
FEAT: Update user data privacy settings

### ISSUE THREAD

**Issue by Ajinx1** [hngprojects/hng_boilerplate_golang_web#309]
## Description
Develop an API endpoint to update data privacy settings with proper authentication and validation.

### Acceptance Criteria

* The endpoint should be accessible at `PUT /api/v1/users/{id}/data-privacy-settings`.
* The endpoint should accept HTTP PUT requests.
* The endpoint should be secured to ensure that only authenticated users with appropriate permissions can update the data.
* Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
* Requests to the endpoint must include a valid authentication token in the Authorization header.

Authorization: Bearer `<token>`

#### Request
* The request body should include the updated data privacy settings.

```json
{
    "profile_visibility": true,
    "share_data_with_partners": true,
    "receive_email_updates": true,
    "enable_2fa": true,
    "use_data_encryption": true,
    "allow_analytics": true,
    "personalized_ads": true
}
```

#### Response
* On successful update, the API should return a 200 OK status code and the updated data privacy settings.

```json
{
    "status": "success",
    "status_code": 200,
    "message": "Data privacy settings updated successfully",
    "data": {
        "id": "0190ff8c-96d7-79e7-a13d-154449084572",
        "user_id": "12345678-1234-1234-1234-123456789012",
        "profile_visibility": true,
        "share_data_with_partners": true,
        "receive_email_updates": true,
        "enable_2fa": true,
        "use_data_encryption": true,
        "allow_analytics": true,
        "personalized_ads": true,
        "created_at": "2024-07-29T18:32:02.135934+01:00",
        "updated_at": "2024-07-30T18:32:02.135934+01:00"
    }
}
```

_Unsuccessful Response:_
```json
{
    "status": "error",
    "status_code": 400,
    "message": "error message"
}
```

_Authorization Error Response:_
```json
{
    "status": "error",
    "status_code": 401,
    "message": "invalid token"
}
```

### Purpose
Provides a backend service that allows authorized users to update data privacy settings with proper authentication and validation.

### Requirements
* Develop server-side logic to update data privacy settings.
* Ensure only users with appropriate permissions can modify the data.
* Implement proper error handling and status code responses.

### Expected Outcome
* API endpoint allows updating of data privacy settings with appropriate authentication and error handling.

### Tasks
* [ ] Create an endpoint `PUT /api/v1/users/{id}/data-privacy-settings` to update data privacy settings.
* [ ] Implement server-side logic to handle successful and failed update requests.
* [ ] Ensure the user has the proper permissions to update the data.
* [ ] Implement proper error handling for various scenarios (unauthorized access, etc.).
* [ ] Write integration tests for updating data privacy settings.
* [ ] Perform security testing to ensure only authorized users can update the data.

### Testing
* Write integration tests for the end-to-end updating of data privacy settings.
* Test various scenarios:
  * Updating data privacy settings.
  * Attempting to update data privacy settings without authentication.
